spring.application.name=backend

# Ustawienia bazy danych (H2 w pamięci)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ustawienia Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Włączenie konsoli H2 (dostępna pod adresem /h2-console podczas działania aplikacji)
spring.h2.console.enabled=true
