spring.application.name=backend

# Ustawienia bazy danych (H2 w pamięci)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ustawienia Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Włączenie konsoli H2 (dostępna pod adresem /h2-console podczas działania aplikacji)
spring.h2.console.enabled=true

# Ustawienia dla klienta EDGAR API (mapowane na EdgarEnvVariablesConfig)
edgar.api.base-url=https://www.sec.gov
# SEC EDGAR wymusza podanie nazwy/firmy oraz adresu e-mail w User-Agent, zaktualizuj te dane na swoje prawdziwe!
edgar.api.user-agent=Barto (codeismyspotter@gmail.com)
edgar.api.tickers-file=/files/company_tickers.json

# --- USTAWIENIA LOGOWANIA ---
# Wycisza "śmieci" (logi informacyjne) z samego Springa, serwera Tomcat i bazy danych
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache.catalina=WARN
logging.level.com.zaxxer.hikari=WARN

# Włącza bardzo szczegółowe logi tylko dla Twojego własnego kodu
logging.level.com.example.backend=DEBUG
